import Image from "next/image";
import Link from "next/link";
import { StatusBadge } from "@/components/ui/status-badge";
import { Surface } from "@/components/ui/surface";
import { formatMoney } from "@/lib/booking-ux";
import { courtDiscoveryCopy } from "@/lib/court-discovery";
import type { Locale } from "@/lib/copy";
import type { Court } from "@/lib/types";

export function CourtCard({court,locale}:{court:Court;locale:Locale}){const t=courtDiscoveryCopy[locale],name=court[locale==="ar"?"name_ar":"name_en"],sport=court.sport?.[locale==="ar"?"name_ar":"name_en"];return <Link href={`/${locale}/courts/${encodeURIComponent(String(court.id))}`} aria-label={`${t.view}: ${name}`} className="focus-ring block min-w-0 rounded-[var(--radius-lg)]"><Surface as="article" variant="interactive" className="grid h-full min-w-0 overflow-hidden p-0 md:grid-cols-[11rem_minmax(0,1fr)] lg:block"><div className="relative min-h-40 bg-[var(--surface-2)] lg:aspect-[16/9] lg:min-h-0">{court.image_url?<Image src={court.image_url} alt="" fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 45vw, 30vw" className="object-cover" unoptimized/>:<div className="flex h-full min-h-40 items-center justify-center bg-[linear-gradient(135deg,var(--surface-2),var(--surface-3))] px-4 text-center text-sm font-bold text-[var(--text-muted)]" aria-label={t.fallback}>{t.fallback}</div>}</div><div className="min-w-0 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><StatusBadge status={court.is_active?"success":"danger"} size="sm">{court.is_active?t.active:t.inactive}</StatusBadge>{sport&&<span className="text-xs text-[var(--text-muted)]" dir="auto">{sport}</span>}</div><h2 className="mt-4 break-words text-xl font-black" dir="auto">{name}</h2><p className="mt-2 break-words text-sm text-[var(--text-muted)]" dir="auto">{court.area}</p><p className="mt-4 text-sm font-bold"><bdi>{formatMoney(locale,court.price_per_hour,court.currency)}</bdi> <span className="font-normal text-[var(--text-muted)]">{t.perHour}</span></p><span className="mt-4 inline-flex min-h-11 items-center font-bold text-[var(--brand)]">{t.view}</span></div></Surface></Link>}
