"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Drawer } from "@/components/ui/drawer";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Surface } from "@/components/ui/surface";
import { courtDiscoveryCopy, courtPublicQuery, type CourtFilters } from "@/lib/court-discovery";
import type { Locale } from "@/lib/copy";

function Fields({locale,filters,id}:{locale:Locale;filters:CourtFilters;id:string}){const t=courtDiscoveryCopy[locale];return <div className="grid gap-5"><Input id={`${id}-search`} name="search" label={t.search} defaultValue={filters.search} maxLength={100}/><Input id={`${id}-area`} name="area" label={t.area} defaultValue={filters.area} maxLength={100}/><div className="grid grid-cols-2 gap-3"><Input id={`${id}-min`} name="min" type="number" min="0" step="0.001" label={t.min} defaultValue={filters.min}/><Input id={`${id}-max`} name="max" type="number" min="0" step="0.001" label={t.max} defaultValue={filters.max}/></div><label className="grid gap-2 text-sm font-bold" htmlFor={`${id}-active`}>{t.status}<Select id={`${id}-active`} name="active" defaultValue={filters.active} fullWidth><option value="">{t.all}</option><option value="true">{t.active}</option><option value="false">{t.inactive}</option></Select></label><div className="grid gap-2"><Button type="submit" size="lg" fullWidth>{t.apply}</Button><Link className="button-link button-link-secondary w-full" href={`/${locale}/courts`}>{t.reset}</Link></div></div>}
export function CourtDiscoveryFilters({locale,filters}:{locale:Locale;filters:CourtFilters}){const t=courtDiscoveryCopy[locale],[open,setOpen]=useState(false),active=[filters.search&&["search",filters.search],filters.area&&["area",filters.area],filters.min&&["min",filters.min],filters.max&&["max",filters.max],filters.active&&["active",filters.active==="true"?t.active:t.inactive]].filter(Boolean)as[string,string][];return <><div className="lg:hidden"><Button type="button" variant="secondary" size="lg" fullWidth onClick={()=>setOpen(true)}><span aria-hidden>☰</span>{t.openFilters}{active.length?` (${active.length})`:""}</Button></div><aside className="hidden lg:row-span-2 lg:block"><Surface variant="elevated" className="sticky top-24 rounded-[var(--radius-xl)] p-6"><div className="mb-6 flex items-center justify-between gap-3"><h2 className="text-xl font-black">{t.filters}</h2>{active.length>0&&<span className="grid size-8 place-items-center rounded-full bg-[var(--brand)] text-xs font-black text-[var(--brand-foreground)]"><bdi>{active.length}</bdi></span>}</div><form action={`/${locale}/courts`} method="get"><Fields locale={locale} filters={filters} id="desktop"/></form></Surface></aside><Drawer open={open} onClose={()=>setOpen(false)} title={t.filters}><form action={`/${locale}/courts`} method="get"><Fields locale={locale} filters={filters} id="mobile"/></form></Drawer>{active.length>0&&<div className="reveal-in col-span-full flex flex-wrap gap-2 lg:col-start-2 lg:col-end-3" aria-label={t.activeFilters}>{active.map(([key,label])=>{const next={...filters,[key]:"",page:1}as CourtFilters;return <Link key={key} className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-full border border-[var(--brand)]/25 bg-[var(--brand)]/10 px-4 text-xs font-bold text-[var(--brand)] transition hover:border-[var(--brand)] hover:bg-[var(--brand)]/15" href={`/${locale}/courts?${courtPublicQuery(next)}`} aria-label={`${t.reset}: ${label}`}><bdi>{label}</bdi><span aria-hidden>×</span></Link>})}</div>}</>}
