import { fireEvent, render, screen, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { MatchExperience } from "@/components/match-experience";
import MatchLoading from "@/app/[locale]/matches/[matchId]/loading";
import { MatchFailure } from "@/app/[locale]/matches/[matchId]/page";
import type { Match, MatchJoinRequest } from "@/lib/types";

const base:Match={id:42,title:"Friday Football",description:"Friendly match.",sport_type:"football",visibility:"public",join_policy:"open",status:"open",skill_level:"all_levels",min_players:8,max_players:14,start_time:"2030-05-10T17:00:00Z",end_time:"2030-05-10T18:30:00Z",created_at:"2030-05-01T10:00:00Z",creator:{id:1,full_name:"Mona Ali"},court:{id:9,name_en:"Green Court",name_ar:"الملعب الأخضر",area:"Kuwait"},approved_participant_count:7,available_spots:7,has_joined:false,current_user_participant_status:null,can_manage:false,booking_id:5};
const pending:MatchJoinRequest={id:70,match_id:42,user_id:12,status:"pending",created_at:"2030-05-01T11:00:00Z",updated_at:"2030-05-01T11:00:00Z",requester:{id:12,full_name:"Omar Said"}};
const response=(data:unknown,ok=true,status=200)=>({ok,status,json:async()=>data});
const view=(match=base,request:MatchJoinRequest|null=null,items:MatchJoinRequest[]=[])=>render(<MatchExperience locale="en" initialMatch={match} initialRequest={request} initialPendingRequests={items}/>);

describe("CM2 MatchExperience",()=>{beforeEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()});
it("renders real details, capacity, lifecycle, and no private fields",()=>{const{container}=view();expect(screen.getByRole("heading",{level:1,name:"Friday Football"})).toBeInTheDocument();expect(screen.getByText("7/14")).toBeInTheDocument();expect(screen.getByText("Open")).toBeInTheDocument();expect(container).not.toHaveTextContent(/email|phone/i)});
it("submits direct join once and trusts server result",async()=>{const fetch=vi.fn().mockResolvedValue(response({...base,has_joined:true,current_user_participant_status:"approved"}));vi.stubGlobal("fetch",fetch);view();fireEvent.click(screen.getByRole("button",{name:"Join match"}));await screen.findByText("Already joined");expect(fetch).toHaveBeenCalledTimes(1);expect(fetch).toHaveBeenCalledWith("/api/matches/42/join",expect.objectContaining({method:"POST"}))});
it("submits approval request payload and locks duplicate submit",async()=>{let resolve!:(value:unknown)=>void;vi.stubGlobal("fetch",vi.fn(()=>new Promise(done=>{resolve=done})));view({...base,join_policy:"approval_required"});const button=screen.getByRole("button",{name:"Request to join"});fireEvent.click(button);expect(button).toBeDisabled();fireEvent.click(button);expect(fetch).toHaveBeenCalledTimes(1);resolve(response(pending));await screen.findByText("Pending approval");expect(fetch).toHaveBeenCalledWith("/api/matches/42/join-requests",expect.objectContaining({body:JSON.stringify({position_code:null})}))});
it("withdraws pending request only after confirmation and success",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({...pending,status:"withdrawn"})));view({...base,join_policy:"approval_required"},pending);fireEvent.click(screen.getByRole("button",{name:"Withdraw request"}));expect(fetch).not.toHaveBeenCalled();const dialog=screen.getByRole("dialog");fireEvent.click(within(dialog).getByRole("button",{name:"Confirm"}));await screen.findByText("Request withdrawn.");expect(fetch).toHaveBeenCalledTimes(1)});
it.each(["full","cancelled","completed"] as const)("blocks actions for %s lifecycle",status=>{view({...base,status,available_spots:status==="full"?0:7});expect(screen.queryByRole("button",{name:/join/i})).toBeNull()});
it("shows manager-only roster and request controls",()=>{view({...base,can_manage:true},null,[pending]);expect(screen.getByText("Omar Said")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Approve"})).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Join match"})).toBeNull()});
it("confirms approval and keeps request on server conflict",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({detail:"raw"},false,409)));view({...base,can_manage:true},null,[pending]);fireEvent.click(screen.getByRole("button",{name:"Approve"}));fireEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Confirm"}));await screen.findByText("Match state changed. Refresh and try again.");expect(screen.getByText("Omar Said")).toBeInTheDocument();expect(screen.queryByText("raw")).toBeNull()});
it("renders Arabic and manager roster without sensitive data",()=>{render(<MatchExperience locale="ar" initialMatch={{...base,can_manage:true}} initialRequest={null} initialPendingRequests={[]} initialParticipants={[{id:1,user_id:1,user_name:"Mona Ali",status:"approved",created_at:base.created_at}]}/>);expect(screen.getByRole("heading",{level:1,name:"Friday Football"})).toBeInTheDocument();expect(screen.getAllByText("المنظم").length).toBeGreaterThan(0)});
it("renders localized loading and safe recovery",async()=>{render(await MatchLoading({params:Promise.resolve({locale:"en"})}));expect(screen.getByText("Loading match details")).toBeInTheDocument();render(<MatchFailure locale="en" message="Match not found."/>);expect(screen.getByRole("link",{name:"Back to matches"})).toHaveAttribute("href","/en/matches")});
});
