import Link from"next/link";import{StatusBadge}from"@/components/ui/status-badge";import{Surface}from"@/components/ui/surface";import{EmptyState}from"@/components/ui/empty-state";import{PageHeader}from"@/components/ui/page-header";import type{Locale}from"@/lib/copy";import type{ProductRoute,RouteClass}from"@/lib/product-routes";
export const ProductPageHeader=PageHeader;
export function FeatureStatusBanner({classification,locale}:{classification:RouteClass;locale:Locale}){const labels={en:{LIVE:"Live",PARTIAL:"In progress",SHELL:"Coming soon",DEFERRED:"Deferred"},ar:{LIVE:"متاح",PARTIAL:"قيد التطوير",SHELL:"قريبًا",DEFERRED:"مؤجل"}}[locale];const tone=classification==="LIVE"?"success":classification==="PARTIAL"?"warning":"neutral";return <div role="status" className="mb-5"><StatusBadge status={tone}>{labels[classification]} · {classification}</StatusBadge></div>}
export function ComingSoonState({route,locale}:{route:ProductRoute;locale:Locale}){return <Surface><EmptyState title={route.title[locale]} description={route.description[locale]}/><p className="px-5 pb-6 text-center text-xs text-[var(--text-muted)]">{locale==="ar"?"لن تعرض هذه الصفحة بيانات أو إجراءات مصطنعة.":"This page does not display simulated data or actions."}</p></Surface>}
export function Breadcrumbs({locale,items}:{locale:Locale;items:{label:string;href?:string}[]}){return <nav aria-label={locale==="ar"?"مسار التنقل":"Breadcrumbs"}><ol className="flex flex-wrap gap-2 text-sm text-[var(--text-muted)]">{items.map((item,i)=><li key={`${item.label}-${i}`}>{item.href?<Link className="focus-ring hover:text-[var(--brand)]" href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}{i<items.length-1&&<span aria-hidden="true" className="ms-2">/</span>}</li>)}</ol></nav>}
export function DataTableShell({title,locale}:{title:string;locale:Locale}){return <Surface as="section"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 text-sm text-[var(--text-muted)]">{locale==="ar"?"لا توجد بيانات متصلة للعرض.":"No connected data to display."}</p></Surface>}
export const MetricEmptyState=({locale}:{locale:Locale})=><EmptyState size="compact" title={locale==="ar"?"لا توجد مؤشرات متاحة":"No metrics available"} description={locale==="ar"?"لن نعرض أرقامًا مصطنعة.":"No fabricated numbers are shown."}/>;
export const StatCard=MetricEmptyState;export const PlayerCard=MetricEmptyState;export const TeamCard=MetricEmptyState;export const TournamentCard=MetricEmptyState;export const NotificationItem=MetricEmptyState;export const PaymentStatusCard=MetricEmptyState;
export function FilterBar({children}:{children?:React.ReactNode}){return <div role="search" className="flex min-h-11 flex-wrap gap-3 rounded-[var(--radius-lg)] border border-[var(--border-strong)] p-3">{children}</div>}
export function SearchField({locale}:{locale:Locale}){return <label className="grid gap-1 text-sm font-bold">{locale==="ar"?"بحث":"Search"}<input disabled className="min-h-11 rounded-[var(--radius-md)] border border-[var(--border-strong)] bg-[var(--surface-2)] px-3" placeholder={locale==="ar"?"غير متاح حاليًا":"Currently unavailable"}/></label>}
export function Pagination({locale}:{locale:Locale}){return <nav aria-label={locale==="ar"?"ترقيم الصفحات":"Pagination"} className="text-sm text-[var(--text-muted)]">{locale==="ar"?"لا توجد صفحات إضافية":"No additional pages"}</nav>}
