import Link from "next/link";
import { CourtCard } from "@/components/court-card";
import { EmptyState } from "@/components/ui/empty-state";
import { Surface } from "@/components/ui/surface";
import { formatDateTime } from "@/lib/booking-ux";
import type { Locale } from "@/lib/copy";
import type { Booking,Court } from "@/lib/types";

export function HomeDashboard({locale,courts,userName,upcoming,bookingsUnavailable=false,courtsUnavailable=false}:{locale:Locale;courts:Court[];userName?:string;upcoming:Booking[];bookingsUnavailable?:boolean;courtsUnavailable?:boolean}) {
  const ar=locale==="ar",sports=[...new Map(courts.flatMap(c=>c.sport?[[c.sport_id,c.sport]]:[])).entries()];
  const t=ar?{hello:userName?`مرحباً، ${userName}`:"مرحباً بك",area:"الكويت",search:"ابحث عن ملعب أو رياضة أو منطقة…",hero:"احجز ملعبك في ثوانٍ",heroText:"اكتشف الملاعب المتاحة واختر وقتك من نظام الحجز.",book:"احجز الآن",upcoming:"حجوزاتك القادمة",all:"عرض الكل",none:"لا توجد حجوزات قادمة",noneText:"ابدأ باكتشاف الملاعب واختر موعداً متاحاً.",sports:"اختر رياضتك",nearby:"ملاعب متاحة",community:"اكتشف مباريات المجتمع",communityText:"اعثر على لاعبين ومباريات عامة متاحة.",open:"استكشف المباريات",error:"تعذر تحميل هذه البيانات حالياً."}:{hello:userName?`Welcome, ${userName}`:"Welcome to MAL3ABY",area:"Kuwait",search:"Search courts, sports, or areas…",hero:"Book your court in seconds",heroText:"Discover active courts and choose a time from the booking system.",book:"Book now",upcoming:"Upcoming bookings",all:"View all",none:"No upcoming bookings",noneText:"Discover courts and choose an available time to get started.",sports:"Choose your sport",nearby:"Available courts",community:"Discover community matches",communityText:"Find players and available public matches.",open:"Explore matches",error:"This data could not be loaded right now."};
  return <div className="home-dashboard page-wrap pb-28 pt-5">
    <header className="home-welcome"><div><p className="text-xs text-[var(--text-muted)]">{t.area} · <span aria-hidden>⌖</span></p><h1 className="mt-1 text-xl font-black" dir="auto">{t.hello}</h1></div></header>
    <form role="search" action={`/${locale}/courts`} className="discovery-search mt-5"><label className="sr-only" htmlFor={`home-search-${locale}`}>{t.search}</label><span aria-hidden>⌕</span><input id={`home-search-${locale}`} name="search" placeholder={t.search} autoComplete="off"/><button type="submit" aria-label={ar?"بحث":"Search"}>→</button></form>
    <section className="home-booking-hero" aria-labelledby="quick-book"><div><p className="eyebrow">MAL3ABY</p><h2 id="quick-book" className="mt-2 max-w-xs text-3xl font-black">{t.hero}</h2><p className="mt-2 max-w-sm text-sm text-[var(--text-secondary)]">{t.heroText}</p><Link className="button-link mt-5" href={`/${locale}/courts`}>{t.book}</Link></div><div className="home-pitch" aria-hidden="true"><span>⚽</span></div></section>
    <section className="home-section" aria-labelledby="upcoming-bookings"><div className="section-compact-heading"><h2 id="upcoming-bookings">{t.upcoming}</h2>{upcoming.length>0&&<Link href={`/${locale}/bookings`}>{t.all}</Link>}</div>{bookingsUnavailable?<p className="state-note">{t.error}</p>:upcoming.length?<div className="grid gap-3">{upcoming.slice(0,2).map(booking=><Surface key={booking.id} className="p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><strong className="block truncate" dir="auto">{booking.court?.[ar?"name_ar":"name_en"]}</strong><time className="mt-1 block text-xs text-[var(--text-muted)]" dateTime={booking.start_time}>{formatDateTime(locale,booking.start_time)}</time></div><Link className="font-bold text-[var(--brand)]" href={`/${locale}/bookings/${booking.id}`}>{ar?"التفاصيل":"Details"}</Link></div></Surface>)}</div>:<Surface className="border-dashed"><EmptyState size="compact" title={t.none} description={t.noneText}/></Surface>}</section>
    <section className="home-section" aria-labelledby="sport-shortcuts"><div className="section-compact-heading"><h2 id="sport-shortcuts">{t.sports}</h2></div>{sports.length?<div className="sport-chip-row">{sports.map(([id,s])=><Link key={id} href={`/${locale}/courts?sport_id=${id}`}>{s[ar?"name_ar":"name_en"]}</Link>)}</div>:<p className="state-note">{courtsUnavailable?t.error:t.noneText}</p>}</section>
    <section className="home-section" aria-labelledby="available-courts"><div className="section-compact-heading"><h2 id="available-courts">{t.nearby}</h2><Link href={`/${locale}/courts`}>{t.all}</Link></div>{courtsUnavailable?<p className="state-note">{t.error}</p>:courts.length?<div className="discovery-results">{courts.slice(0,3).map(c=><CourtCard key={c.id} court={c} locale={locale}/>)}</div>:<Surface className="border-dashed"><EmptyState size="compact" title={ar?"لا توجد ملاعب متاحة":"No courts available"}/></Surface>}</section>
    <section className="home-community"><div><h2 className="text-xl font-black">{t.community}</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{t.communityText}</p></div><Link className="button-link button-link-secondary" href={`/${locale}/matches`}>{t.open}</Link></section>
  </div>;
}
