import Link from "next/link";
import { Surface } from "@/components/ui/surface";
import type { Locale } from "@/lib/copy";
import type { Court } from "@/lib/types";

export function ProductSections({locale,courts,isLoggedIn,isOwner}:{locale:Locale;courts:Court[];isLoggedIn:boolean;isOwner:boolean}) {
  const sports=[...new Map(courts.flatMap(c=>c.sport?[[c.sport_id,{...c.sport,id:c.sport_id}]]:[])).values()];
  const ownerPath=isOwner?"owner":isLoggedIn?"profile":"login";
  const ar=locale==="ar";
  const t=ar?{sports:"الرياضات المتاحة",sportsDesc:"اختر رياضتك واعرض الملاعب المتاحة فعلياً.",empty:"ستظهر الرياضات عند توفر ملاعب نشطة.",community:"العب مع المجتمع",communityDesc:"اكتشف المباريات العامة، أنشئ مباراة، وتابع طلبات الانضمام.",matches:"استكشف المباريات",communityLink:"صفحة المجتمع",owner:"تدير ملعباً؟",ownerDesc:"أدر الملاعب والأسعار والتوفر والحجوزات من مساحة المالك.",ownerLink:isLoggedIn?"الملف الشخصي":"تسجيل الدخول",trust:"حجز واضح ومحمي",trustItems:["السعر والحالة يحددهما الخادم","الجلسة محفوظة في ملف ارتباط آمن","العربية والإنجليزية مدعومتان"]}:{sports:"Available sports",sportsDesc:"Choose a sport and browse courts that are actually available.",empty:"Sports appear when active courts are available.",community:"Play with the community",communityDesc:"Discover public matches, create one, and follow join requests.",matches:"Explore matches",communityLink:"Community hub",owner:"Manage a court?",ownerDesc:"Manage courts, pricing, availability, and bookings from the owner workspace.",ownerLink:isLoggedIn?"Your profile":"Sign in",trust:"Clear, protected booking",trustItems:["Server-authoritative price and status","Session stored in a secure cookie","Arabic and English supported"]};
  return <>
    <section className="page-wrap py-12 sm:py-16" aria-labelledby="sports-title"><div className="max-w-2xl"><h2 id="sports-title" className="text-2xl font-black sm:text-3xl">{t.sports}</h2><p className="mt-2 text-[var(--text-muted)]">{t.sportsDesc}</p></div>{sports.length?<div className="mt-6 flex flex-wrap gap-3">{sports.map(s=><Link key={s.id} className="focus-ring inline-flex min-h-11 items-center rounded-full border border-[var(--border-strong)] bg-[var(--surface-1)] px-5 text-sm font-bold transition hover:-translate-y-0.5 hover:border-[var(--brand)] hover:text-[var(--brand)] motion-reduce:transform-none" href={`/${locale}/courts?sport_id=${s.id}`}>{s[ar?"name_ar":"name_en"]}</Link>)}</div>:<p className="mt-4 text-[var(--text-muted)]">{t.empty}</p>}</section>
    <section className="border-y border-[var(--border-strong)] bg-[var(--surface-1)]"><div className="page-wrap grid gap-5 py-12 md:grid-cols-2"><Surface variant="elevated" className="p-6 sm:p-8"><h2 className="text-2xl font-black">{t.community}</h2><p className="mt-3 leading-7 text-[var(--text-muted)]">{t.communityDesc}</p><div className="mt-6 flex flex-wrap gap-3"><Link className="button-link" href={`/${locale}/matches`}>{t.matches}</Link><Link className="button-link button-link-secondary" href={`/${locale}/community`}>{t.communityLink}</Link></div></Surface><Surface className="p-6 sm:p-8"><h2 className="text-2xl font-black">{t.owner}</h2><p className="mt-3 leading-7 text-[var(--text-muted)]">{t.ownerDesc}</p><Link className="button-link button-link-secondary mt-6" href={`/${locale}/${ownerPath}`}>{isOwner?(ar?"مساحة المالك":"Owner workspace"):t.ownerLink}</Link></Surface></div></section>
    <section className="page-wrap py-12 sm:py-16" aria-labelledby="trust-title"><h2 id="trust-title" className="text-2xl font-black sm:text-3xl">{t.trust}</h2><ul className="mt-6 grid gap-3 sm:grid-cols-3">{t.trustItems.map((item,i)=><li key={item} className="reveal-in rounded-[var(--radius-lg)] border border-[var(--border-strong)] bg-[var(--surface-1)] p-5 text-sm font-semibold" style={{animationDelay:`${i*50}ms`}}><span className="me-2 text-[var(--brand)]" aria-hidden>✓</span>{item}</li>)}</ul></section>
  </>;
}
