"""create_court_pricing_tables

Revision ID: 70e32c8bda52
Revises: 89bf7f864362
Create Date: 2026-07-28 23:05:44.701249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e32c8bda52'
down_revision: Union[str, Sequence[str], None] = '89bf7f864362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_date_price_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('override_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_date_price_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_date_price_overrides_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_date_price_overrides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_date_price_overrides_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_date_price_overrides_local_date'), ['local_date'], unique=False)

    op.create_table('court_pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(weekday IS NULL) OR (weekday >= 0 AND weekday <= 6)', name='check_pricing_rule_weekday_valid'),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from', name='check_pricing_rule_valid_date_range'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_pricing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_pricing_rules_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_pricing_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_pricing_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_pricing_rules_weekday'), ['weekday'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price_per_hour', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='KWD'))
        batch_op.add_column(sa.Column('pricing_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pricing_calculated_at', sa.DateTime(timezone=True), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('pricing_calculated_at')
        batch_op.drop_column('pricing_breakdown')
        batch_op.drop_column('currency')
        batch_op.drop_column('base_price_per_hour')

    with op.batch_alter_table('court_pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_pricing_rules_weekday'))
        batch_op.drop_index(batch_op.f('ix_court_pricing_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_court_pricing_rules_id'))
        batch_op.drop_index(batch_op.f('ix_court_pricing_rules_court_id'))

    op.drop_table('court_pricing_rules')
    with op.batch_alter_table('court_date_price_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_date_price_overrides_local_date'))
        batch_op.drop_index(batch_op.f('ix_court_date_price_overrides_is_active'))
        batch_op.drop_index(batch_op.f('ix_court_date_price_overrides_id'))
        batch_op.drop_index(batch_op.f('ix_court_date_price_overrides_court_id'))

    op.drop_table('court_date_price_overrides')
    # ### end Alembic commands ###
