"""create_court_availability_tables

Revision ID: 89bf7f864362
Revises: ba64a5d872fe
Create Date: 2026-07-28 22:34:07.730435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bf7f864362'
down_revision: Union[str, Sequence[str], None] = 'ba64a5d872fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_availability_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('minimum_booking_minutes', sa.Integer(), nullable=False),
    sa.Column('maximum_booking_minutes', sa.Integer(), nullable=False),
    sa.Column('booking_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('maximum_advance_booking_days', sa.Integer(), nullable=False),
    sa.Column('minimum_advance_booking_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('booking_interval_minutes > 0', name='check_interval_mins_gt_0'),
    sa.CheckConstraint('buffer_minutes >= 0', name='check_buffer_mins_gte_0'),
    sa.CheckConstraint('maximum_advance_booking_days >= 1', name='check_max_advance_days_gte_1'),
    sa.CheckConstraint('maximum_booking_minutes >= minimum_booking_minutes', name='check_max_gte_min_booking_mins'),
    sa.CheckConstraint('minimum_advance_booking_minutes >= 0', name='check_min_advance_mins_gte_0'),
    sa.CheckConstraint('minimum_booking_minutes >= 30', name='check_min_booking_mins_gte_30'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_availability_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_availability_rules_court_id'), ['court_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_court_availability_rules_id'), ['id'], unique=False)

    op.create_table('court_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('closure_type', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_court_closure_end_after_start'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_closures_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_closures_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_closures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_closures_start_time'), ['start_time'], unique=False)

    op.create_table('court_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='check_working_hours_weekday_range'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'weekday', name='uq_court_working_hours_weekday')
    )
    with op.batch_alter_table('court_working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_working_hours_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_working_hours_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court_working_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_working_hours_id'))
        batch_op.drop_index(batch_op.f('ix_court_working_hours_court_id'))

    op.drop_table('court_working_hours')
    with op.batch_alter_table('court_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_closures_start_time'))
        batch_op.drop_index(batch_op.f('ix_court_closures_id'))
        batch_op.drop_index(batch_op.f('ix_court_closures_end_time'))
        batch_op.drop_index(batch_op.f('ix_court_closures_court_id'))

    op.drop_table('court_closures')
    with op.batch_alter_table('court_availability_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_availability_rules_id'))
        batch_op.drop_index(batch_op.f('ix_court_availability_rules_court_id'))

    op.drop_table('court_availability_rules')
    # ### end Alembic commands ###
