"""add_booking_hold_and_lifecycle_fields

Revision ID: ae676d58b47b
Revises: 70e32c8bda52
Create Date: 2026-07-28 23:30:56.702772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae676d58b47b'
down_revision: Union[str, Sequence[str], None] = '70e32c8bda52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))

        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_bookings_hold_expires_at'), ['hold_expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_hold_expires_at'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('expired_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('hold_expires_at')

    # ### end Alembic commands ###
