import type { Booking, BookingStatus } from "@/lib/types";
import type { Locale } from "@/lib/copy";

export const bookingUx = {
  en: { perHour: "per hour", location: "Location", priceFrom: "Base price", timezone: "Times shown in Asia/Kuwait", selected: "Selected time", duration: "Duration", minutes: "minutes", holdCreated: "Your temporary reservation is held while trusted confirmation is pending.", holdExpired: "This reservation hold has expired.", awaiting: "Confirmation is completed only by the trusted booking process. You can track this reservation in My Bookings.", backBookings: "Return to My Bookings", cancelHold: "Release hold", cancelBooking: "Cancel booking", cancelling: "Cancelling…", cancelError: "Could not cancel this booking. Please try again.", lifecycle: "What happens next", confirmedOnly: "This page is available only for confirmed bookings.", upcoming: "Upcoming", history: "Past and completed", closed: "Cancelled and expired", created: "Created", reason: "Cancellation information", viewCourt: "View court", noGroup: "No bookings in this group.", selectedSummary: "Selected booking time", loadCourts: "Loading courts", loadCourt: "Loading court", loadBookings: "Loading bookings", loadBooking: "Loading booking", serviceError: "The service is unavailable right now. Please try again.", resultCount: (n:number) => `${n} ${n === 1 ? "court" : "courts"}` },
  ar: { perHour: "لكل ساعة", location: "الموقع", priceFrom: "السعر الأساسي", timezone: "الأوقات معروضة بتوقيت آسيا/الكويت", selected: "الوقت المختار", duration: "المدة", minutes: "دقيقة", holdCreated: "موعدك محجوز مؤقتًا بانتظار التأكيد عبر الإجراء الموثوق.", holdExpired: "انتهت صلاحية هذا الحجز المؤقت.", awaiting: "يتم التأكيد فقط عبر إجراء الحجز الموثوق. يمكنك متابعة الحجز في حجوزاتي.", backBookings: "العودة إلى حجوزاتي", cancelHold: "إلغاء الحجز المؤقت", cancelBooking: "إلغاء الحجز", cancelling: "جارٍ الإلغاء…", cancelError: "تعذر إلغاء الحجز. حاول مرة أخرى.", lifecycle: "الخطوة التالية", confirmedOnly: "هذه الصفحة متاحة للحجوزات المؤكدة فقط.", upcoming: "القادمة", history: "السابقة والمكتملة", closed: "الملغاة والمنتهية", created: "تاريخ الإنشاء", reason: "معلومات الإلغاء", viewCourt: "عرض الملعب", noGroup: "لا توجد حجوزات في هذه المجموعة.", selectedSummary: "وقت الحجز المختار", loadCourts: "جارٍ تحميل الملاعب", loadCourt: "جارٍ تحميل الملعب", loadBookings: "جارٍ تحميل الحجوزات", loadBooking: "جارٍ تحميل الحجز", serviceError: "الخدمة غير متاحة حاليًا. حاول مرة أخرى.", resultCount: (n:number) => `${n} ${n === 1 ? "ملعب" : "ملاعب"}` },
};

export function formatDateTime(locale: Locale, value: string, timeOnly = false) { const options: Intl.DateTimeFormatOptions = timeOnly ? { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Kuwait" } : { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kuwait" }; return new Intl.DateTimeFormat(locale === "ar" ? "ar-KW" : "en-KW", options).format(new Date(value)); }
export function formatMoney(locale: Locale, amount: string, currency: string) { const value = Number(amount); return Number.isFinite(value) ? new Intl.NumberFormat(locale === "ar" ? "ar-KW" : "en-KW", { style: "currency", currency }).format(value) : `${amount} ${currency}`; }
export function durationMinutes(start: string, end: string) { return Math.round((Date.parse(end) - Date.parse(start)) / 60000); }
export function bookingGroup(booking: Booking): "upcoming"|"history"|"closed" { if (["cancelled","expired","rejected","refunded"].includes(booking.status)) return "closed"; if (booking.status === "completed" || Date.parse(booking.end_time) < Date.now()) return "history"; return "upcoming"; }
export const statusExplanation = (locale: Locale, status: BookingStatus) => { const en: Record<BookingStatus,string> = { pending:"The request is awaiting venue review.",pending_payment:"The temporary hold awaits trusted confirmation.",confirmed:"The reservation is confirmed.",cancelled:"The reservation was cancelled.",expired:"The temporary hold expired.",completed:"The reservation was completed.",rejected:"The reservation was not accepted.",refunded:"The reservation amount was refunded." }; const ar: Record<BookingStatus,string> = { pending:"الطلب بانتظار مراجعة الملعب.",pending_payment:"الحجز المؤقت بانتظار التأكيد الموثوق.",confirmed:"تم تأكيد الحجز.",cancelled:"تم إلغاء الحجز.",expired:"انتهت صلاحية الحجز المؤقت.",completed:"اكتمل الحجز.",rejected:"لم تتم الموافقة على الحجز.",refunded:"تم استرداد مبلغ الحجز." }; return (locale === "ar" ? ar : en)[status]; };
