export const copy = {
  ar: {
    brand: "ملعبي",
    courts: "الملاعب",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    profile: "حسابي",
    bookings: "حجوزاتي",
    hero: "احجز ملعبك. العب بطريقتك.",
    discover: "اكتشف الملاعب",
    featured: "ملاعب متاحة",
    reviews: "تقييمات موثقة",
    logout: "تسجيل الخروج",
    price: "د.ك / ساعة",
    empty: "لا توجد ملاعب متاحة الآن",
    back: "العودة للملاعب",
    navHome: "الرئيسية",
    navCourts: "الملاعب",
    navBookings: "حجوزاتي",
    navProfile: "حسابي",
    navLogin: "الدخول",
    switchLang: "تغيير إلى الإنجليزية",
    switchLangShort: "EN",
    matchBack: "العودة إلى الملاعب",
    matchDetails: "تفاصيل المباراة",
    matchSport: "الرياضة",
    matchVenue: "الملعب",
    matchDate: "التاريخ",
    matchTime: "الوقت",
    matchOrganizer: "المنظم",
    matchCapacity: "السعة",
    matchJoined: "اللاعبون المنضمون",
    matchAvailable: "الأماكن المتاحة",
    matchStatus: "حالة المباراة",
    matchDescription: "الوصف",
    matchPlayers: "لاعب",
    matchJoin: "انضم إلى المباراة",
    matchWithdraw: "سحب الطلب",
    matchLeave: "مغادرة المباراة",
    matchJoining: "جارٍ إرسال الطلب...",
    matchWithdrawing: "جارٍ سحب الطلب...",
    matchLeaving: "جارٍ المغادرة...",
    matchRequestPending: "طلبك قيد المراجعة.",
    matchRequestApproved: "تمت الموافقة على انضمامك.",
    matchRequestRejected: "تم رفض طلب انضمامك.",
    matchAlreadyJoined: "أنت منضم إلى هذه المباراة.",
    matchOrganizerView: "أنت منظم هذه المباراة.",
    matchRequests: "طلبات الانضمام",
    matchNoRequests: "لا توجد طلبات معلقة",
    matchNoRequestsDesc: "ستظهر طلبات اللاعبين الجديدة هنا.",
    matchApprove: "قبول",
    matchReject: "رفض",
    matchActionError: "تعذّر إكمال الإجراء. حاول مرة أخرى.",
    matchLoadError: "تعذّر تحميل تفاصيل المباراة.",
    matchUnauthorized: "سجّل الدخول لعرض تفاصيل المباراة.",
    matchForbidden: "ليس لديك صلاحية لعرض هذه المباراة.",
    matchNotFound: "المباراة غير موجودة.",
    matchLoading: "جارٍ تحميل تفاصيل المباراة",
    matchOpen: "مفتوحة",
    matchFull: "مكتملة العدد",
    matchCancelled: "ملغاة",
    matchCompleted: "منتهية",
    matchPending: "قيد المراجعة",
    matchApproved: "مقبول",
    matchRejected: "مرفوض",
    matchLogin: "تسجيل الدخول",

    // Homepage Hero
    heroEyebrow: "الحجز الرياضي في الكويت",
    heroHeadline: "احجز ملعبك. العب بطريقتك.",
    heroSubline: "اكتشف الملاعب المتاحة، اختر الوقت المناسب، واحتفظ بحجوزاتك في مكان واحد.",
    heroCta: "اكتشف الملاعب",
    heroCtaSecondary: "حجوزاتي",
    heroCtaLogin: "تسجيل الدخول للحجز",

    // Featured Courts
    featuredEyebrow: "استكشف",
    featuredTitle: "ملاعب متاحة",
    featuredViewAll: "عرض الكل",
    featuredLoading: "جاري تحميل الملاعب...",
    featuredEmpty: "لا توجد ملاعب متاحة حالياً",
    featuredEmptyDesc: "تحقق مرة أخرى لاحقاً أو تواصل معنا.",
    featuredError: "تعذّر تحميل الملاعب، يُرجى المحاولة مرة أخرى.",
    priceUnit: "د.ك / ساعة",

    // How It Works
    howTitle: "كيف يعمل ملعبي؟",
    howStep1Title: "اكتشف ملعبك",
    howStep1Desc: "تصفّح الملاعب الرياضية المتاحة وابحث عن الأنسب لك.",
    howStep2Title: "اختر الوقت",
    howStep2Desc: "اختر الوقت المناسب من الفترات المتاحة الفعلية.",
    howStep3Title: "أكّد الحجز",
    howStep3Desc: "احجز بسهولة واحتفظ بتفاصيل حجزك في مكانٍ واحد.",

    // Why Mal3by
    whyTitle: "لماذا ملعبي؟",
    whyBenefit1Title: "بحث سهل",
    whyBenefit1Desc: "استعرض الملاعب بحسب الرياضة والموقع والتوفر.",
    whyBenefit2Title: "إدارة الحجوزات",
    whyBenefit2Desc: "تابع حجوزاتك وأوقاتها من لوحة تحكم واحدة.",
    whyBenefit3Title: "عربي وإنجليزي",
    whyBenefit3Desc: "المنصة تدعم اللغة العربية والإنجليزية بالكامل.",
    whyBenefit4Title: "متوافق مع الجوّال",
    whyBenefit4Desc: "تجربة سلسة على الهاتف والحاسوب.",

    // Final CTA
    finalCtaTitle: "جاهز للعب؟",
    finalCtaDesc: "ابدأ الآن واستعرض الملاعب المتاحة.",
    finalCtaButton: "استعرض الملاعب",

    // Footer
    footerTagline: "ملعبي · الكويت",
  },
  en: {
    brand: "Mal3by",
    courts: "Courts",
    login: "Log in",
    register: "Create account",
    profile: "Profile",
    bookings: "My Bookings",
    hero: "Book your court. Play your way.",
    discover: "Explore courts",
    featured: "Available courts",
    reviews: "Verified reviews",
    logout: "Log out",
    price: "KWD / hour",
    empty: "No courts available right now",
    back: "Back to courts",
    navHome: "Home",
    navCourts: "Courts",
    navBookings: "Bookings",
    navProfile: "Profile",
    navLogin: "Log in",
    switchLang: "Switch to Arabic",
    switchLangShort: "العربية",
    matchBack: "Back to courts",
    matchDetails: "Match details",
    matchSport: "Sport",
    matchVenue: "Venue",
    matchDate: "Date",
    matchTime: "Time",
    matchOrganizer: "Organizer",
    matchCapacity: "Capacity",
    matchJoined: "Joined players",
    matchAvailable: "Available spots",
    matchStatus: "Match status",
    matchDescription: "Description",
    matchPlayers: "players",
    matchJoin: "Join match",
    matchWithdraw: "Withdraw request",
    matchLeave: "Leave match",
    matchJoining: "Sending request...",
    matchWithdrawing: "Withdrawing request...",
    matchLeaving: "Leaving match...",
    matchRequestPending: "Your request is pending review.",
    matchRequestApproved: "Your place is approved.",
    matchRequestRejected: "Your join request was rejected.",
    matchAlreadyJoined: "You already joined this match.",
    matchOrganizerView: "You organize this match.",
    matchRequests: "Join requests",
    matchNoRequests: "No pending requests",
    matchNoRequestsDesc: "New player requests will appear here.",
    matchApprove: "Approve",
    matchReject: "Reject",
    matchActionError: "Could not complete the action. Please try again.",
    matchLoadError: "Could not load match details.",
    matchUnauthorized: "Log in to view match details.",
    matchForbidden: "You do not have access to this match.",
    matchNotFound: "Match not found.",
    matchLoading: "Loading match details",
    matchOpen: "Open",
    matchFull: "Full",
    matchCancelled: "Cancelled",
    matchCompleted: "Completed",
    matchPending: "Pending",
    matchApproved: "Approved",
    matchRejected: "Rejected",
    matchLogin: "Log in",

    // Homepage Hero
    heroEyebrow: "KUWAIT SPORTS BOOKING",
    heroHeadline: "Book your court. Play your way.",
    heroSubline: "Find available courts, choose a real time slot, and manage all your bookings in one place.",
    heroCta: "Explore Courts",
    heroCtaSecondary: "My Bookings",
    heroCtaLogin: "Log in to Book",

    // Featured Courts
    featuredEyebrow: "DISCOVER",
    featuredTitle: "Available Courts",
    featuredViewAll: "View all",
    featuredLoading: "Loading courts...",
    featuredEmpty: "No courts available right now",
    featuredEmptyDesc: "Check back soon or reach out to us.",
    featuredError: "Could not load courts. Please try again.",
    priceUnit: "KWD / hr",

    // How It Works
    howTitle: "How Mal3by Works",
    howStep1Title: "Find a Court",
    howStep1Desc: "Browse available sports courts and find the right one for you.",
    howStep2Title: "Pick a Slot",
    howStep2Desc: "Choose from real available time slots that suit your schedule.",
    howStep3Title: "Confirm Booking",
    howStep3Desc: "Book instantly and keep all your booking details in one place.",

    // Why Mal3by
    whyTitle: "Why Mal3by?",
    whyBenefit1Title: "Easy Discovery",
    whyBenefit1Desc: "Filter courts by sport, location, and availability.",
    whyBenefit2Title: "Booking Management",
    whyBenefit2Desc: "Track your upcoming and past bookings from one dashboard.",
    whyBenefit3Title: "Arabic & English",
    whyBenefit3Desc: "Full bilingual support for Arabic and English speakers.",
    whyBenefit4Title: "Mobile Friendly",
    whyBenefit4Desc: "A smooth experience on both phone and desktop.",

    // Final CTA
    finalCtaTitle: "Ready to Play?",
    finalCtaDesc: "Start now and browse available courts near you.",
    finalCtaButton: "Browse Courts",

    // Footer
    footerTagline: "Mal3by · Kuwait",
  },
} as const;

export type Locale = keyof typeof copy;
