export const copy = {
  ar: {
    brand: "ملعبي",
    courts: "الملاعب",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    profile: "حسابي",
    bookings: "حجوزاتي",
    hero: "احجز ملعبك. العب بطريقتك.",
    discover: "اكتشف الملاعب",
    featured: "ملاعب متاحة",
    reviews: "تقييمات موثقة",
    logout: "تسجيل الخروج",
    price: "د.ك / ساعة",
    empty: "لا توجد ملاعب متاحة الآن",
    back: "العودة للملاعب",
    navHome: "الرئيسية",
    navCourts: "الملاعب",
    navBookings: "حجوزاتي",
    navProfile: "حسابي",
    navLogin: "الدخول",
    switchLang: "تغيير إلى الإنجليزية",
    switchLangShort: "EN",
  },
  en: {
    brand: "Mal3by",
    courts: "Courts",
    login: "Log in",
    register: "Create account",
    profile: "Profile",
    bookings: "My Bookings",
    hero: "Book your court. Play your way.",
    discover: "Explore courts",
    featured: "Available courts",
    reviews: "Verified reviews",
    logout: "Log out",
    price: "KWD / hour",
    empty: "No courts available right now",
    back: "Back to courts",
    navHome: "Home",
    navCourts: "Courts",
    navBookings: "Bookings",
    navProfile: "Profile",
    navLogin: "Log in",
    switchLang: "Switch to Arabic",
    switchLangShort: "العربية",
  },
} as const;

export type Locale = keyof typeof copy;
