import type { Locale } from "@/lib/copy";
import type { Court } from "@/lib/types";

export const COURT_PAGE_SIZE=12;
export type CourtFilters={search:string;area:string;min:string;max:string;active:""|"true"|"false";page:number};
const first=(value:string|string[]|undefined)=>Array.isArray(value)?value[0]:value??"";
const money=(value:string)=>/^\d{1,6}(\.\d{1,3})?$/.test(value)?value:"";
export function parseCourtFilters(input:Record<string,string|string[]|undefined>):CourtFilters{const active=first(input.active);return{search:first(input.search).trim().slice(0,100),area:first(input.area).trim().slice(0,100),min:money(first(input.min)),max:money(first(input.max)),active:active==="true"||active==="false"?active:"",page:Math.max(1,Math.min(10000,Number.parseInt(first(input.page)||"1",10)||1))}}
export function courtBackendQuery(filters:CourtFilters){const query=new URLSearchParams();if(filters.search)query.set("search",filters.search);if(filters.area)query.set("area",filters.area);if(filters.min)query.set("min_price",filters.min);if(filters.max)query.set("max_price",filters.max);if(filters.active)query.set("is_active",filters.active);query.set("skip",String((filters.page-1)*COURT_PAGE_SIZE));query.set("limit",String(COURT_PAGE_SIZE+1));return query}
export function courtPublicQuery(filters:CourtFilters){const query=new URLSearchParams();for(const[key,value]of Object.entries(filters)){if(key==="page"&&value!==1)query.set(key,String(value));else if(key!=="page"&&value!=="")query.set(key,String(value))}return query.toString()}
export function isCourt(value:unknown):value is Court{if(!value||typeof value!=="object")return false;const court=value as Partial<Court>;return Number.isInteger(court.id)&&typeof court.name_en==="string"&&typeof court.name_ar==="string"&&typeof court.area==="string"&&typeof court.price_per_hour==="string"&&typeof court.currency==="string"&&typeof court.is_active==="boolean"}
export function isCourtArray(value:unknown):value is Court[]{return Array.isArray(value)&&value.every(isCourt)}

export const courtDiscoveryCopy={
 en:{eyebrow:"Explore",title:"Courts",description:"Choose your court, check real availability, and book with ease.",results:(n:number)=>`${n} courts on this page`,filters:"Filters",openFilters:"Open filters",search:"Search by court name",area:"Area",min:"Minimum hourly price",max:"Maximum hourly price",status:"Status",all:"All",active:"Available",inactive:"Unavailable",apply:"Apply filters",reset:"Reset filters",activeFilters:"Active filters",empty:"No courts are currently available",emptyText:"Courts will appear here when they are added and activated.",none:"No matching results",noneText:"Try changing your search or removing some filters.",errorTitle:"Courts could not be loaded",network:"Could not reach the courts service. Check your connection and retry.",invalid:"The courts service returned an invalid response.",service:"Courts service is temporarily unavailable.",unauthorized:"This request could not be authorized.",retry:"Retry",home:"Return home",view:"View court",previous:"Previous",next:"Next",page:"Page",fallback:"Court image unavailable",perHour:"per hour"},
 ar:{eyebrow:"استكشف",title:"الملاعب",description:"اختر ملعبك ثم تحقق من المواعيد المتاحة واحجز بسهولة.",results:(n:number)=>`${n} ملعب في هذه الصفحة`,filters:"الفلاتر",openFilters:"فتح الفلاتر",search:"ابحث باسم الملعب",area:"المنطقة",min:"أقل سعر للساعة",max:"أعلى سعر للساعة",status:"الحالة",all:"الكل",active:"متاح",inactive:"غير متاح",apply:"تطبيق الفلاتر",reset:"إزالة الفلاتر",activeFilters:"الفلاتر النشطة",empty:"لا توجد ملاعب متاحة حاليًا",emptyText:"سيتم عرض الملاعب هنا عند إضافتها وتفعيلها.",none:"لا توجد نتائج مطابقة",noneText:"جرّب تغيير البحث أو إزالة بعض الفلاتر.",errorTitle:"تعذّر تحميل الملاعب",network:"تعذّر الاتصال بخدمة الملاعب. تحقق من اتصالك وحاول مجددًا.",invalid:"أعادت خدمة الملاعب استجابة غير صالحة.",service:"خدمة الملاعب غير متاحة مؤقتًا.",unauthorized:"تعذّر التحقق من صلاحية هذا الطلب.",retry:"إعادة المحاولة",home:"العودة للرئيسية",view:"عرض الملعب",previous:"السابق",next:"التالي",page:"الصفحة",fallback:"صورة الملعب غير متاحة",perHour:"للساعة"}
} satisfies Record<Locale,unknown>;
