import type { JoinRequestStatus, Match, MatchStatus, ParticipantStatus } from "@/lib/types";
import type { Locale } from "@/lib/copy";

export const matchCommunityCopy = {
  en: {
    details:"Match details", back:"Back to matches", sport:"Sport", venue:"Venue", area:"Area", date:"Date", time:"Time", host:"Host", capacity:"Capacity", joined:"Joined", available:"Available", skill:"Skill level", visibility:"Visibility", description:"About this match", booking:"Booking reference", participants:"Participants", noParticipants:"No approved participants to display.", requests:"Join requests", noRequests:"No pending requests", noRequestsText:"New player requests will appear here.", requestJoin:"Request to join", join:"Join match", withdraw:"Withdraw request", leave:"Leave match", manage:"Manage requests", pending:"Pending approval", alreadyJoined:"Already joined", full:"Match is full", closed:"Match is closed", organizer:"You organize this match.", approve:"Approve", reject:"Reject", confirmWithdraw:"Withdraw join request?", confirmApprove:"Approve this request?", confirmReject:"Reject this request?", confirmLeave:"Leave this match?", confirm:"Confirm", cancel:"Cancel", actionError:"Could not complete this action. Please try again.", conflict:"Match state changed. Refresh and try again.", invalidPosition:"Selected position is unavailable.", unauthorized:"Log in to continue.", notFound:"Match not found.", loadError:"Could not load match details.", retry:"Retry", myMatches:"My matches", myMatchesText:"Matches you created or joined.", created:"Created by me", joinedGroup:"Joined", upcoming:"Upcoming", completed:"Completed", cancelled:"Cancelled", pendingRequests:"Pending requests", noGroup:"No matches in this group.", myRequests:"My join requests", myRequestsText:"Track and manage your real join requests.", noMyRequests:"No join requests yet.", position:"Requested position", createdAt:"Submitted", reviewedAt:"Reviewed", viewMatch:"View match", unknownMatch:"Match", withdrawn:"Withdrawn", expired:"Expired", approved:"Approved", rejected:"Rejected", open:"Open", public:"Public", private:"Private", allLevels:"All levels", beginner:"Beginner", intermediate:"Intermediate", advanced:"Advanced", player:"Player", hostBadge:"Host", loading:"Loading", successWithdraw:"Request withdrawn.", successApprove:"Request approved.", successReject:"Request rejected.", unknownPosition:"Other position",
  },
  ar: {
    details:"تفاصيل المباراة", back:"العودة إلى المباريات", sport:"الرياضة", venue:"الملعب", area:"المنطقة", date:"التاريخ", time:"الوقت", host:"المنظم", capacity:"السعة", joined:"المنضمون", available:"المتاح", skill:"مستوى المهارة", visibility:"الظهور", description:"عن المباراة", booking:"مرجع الحجز", participants:"المشاركون", noParticipants:"لا يوجد مشاركون مقبولون لعرضهم.", requests:"طلبات الانضمام", noRequests:"لا توجد طلبات معلقة", noRequestsText:"ستظهر طلبات اللاعبين الجديدة هنا.", requestJoin:"طلب الانضمام", join:"انضم إلى المباراة", withdraw:"سحب الطلب", leave:"مغادرة المباراة", manage:"إدارة الطلبات", pending:"بانتظار الموافقة", alreadyJoined:"منضم بالفعل", full:"المباراة مكتملة العدد", closed:"المباراة مغلقة", organizer:"أنت منظم هذه المباراة.", approve:"قبول", reject:"رفض", confirmWithdraw:"هل تريد سحب طلب الانضمام؟", confirmApprove:"هل تريد قبول هذا الطلب؟", confirmReject:"هل تريد رفض هذا الطلب؟", confirmLeave:"هل تريد مغادرة المباراة؟", confirm:"تأكيد", cancel:"إلغاء", actionError:"تعذّر إكمال الإجراء. حاول مرة أخرى.", conflict:"تغيّرت حالة المباراة. حدّث الصفحة وحاول مجددًا.", invalidPosition:"المركز المختار غير متاح.", unauthorized:"سجّل الدخول للمتابعة.", notFound:"المباراة غير موجودة.", loadError:"تعذّر تحميل تفاصيل المباراة.", retry:"إعادة المحاولة", myMatches:"مبارياتي", myMatchesText:"المباريات التي أنشأتها أو انضممت إليها.", created:"أنشأتها", joinedGroup:"انضممت إليها", upcoming:"القادمة", completed:"المنتهية", cancelled:"الملغاة", pendingRequests:"طلبات معلقة", noGroup:"لا توجد مباريات في هذه المجموعة.", myRequests:"طلبات انضمامي", myRequestsText:"تابع طلبات انضمامك الحقيقية وأدرها.", noMyRequests:"لا توجد طلبات انضمام بعد.", position:"المركز المطلوب", createdAt:"تاريخ الإرسال", reviewedAt:"تاريخ المراجعة", viewMatch:"عرض المباراة", unknownMatch:"مباراة", withdrawn:"مسحوب", expired:"منتهي الصلاحية", approved:"مقبول", rejected:"مرفوض", open:"مفتوحة", public:"عامة", private:"خاصة", allLevels:"كل المستويات", beginner:"مبتدئ", intermediate:"متوسط", advanced:"متقدم", player:"لاعب", hostBadge:"المنظم", loading:"جارٍ التحميل", successWithdraw:"تم سحب الطلب.", successApprove:"تم قبول الطلب.", successReject:"تم رفض الطلب.", unknownPosition:"مركز آخر",
  },
} as const;

export function lifecycleLabel(locale:Locale,status:MatchStatus){const t=matchCommunityCopy[locale];return ({open:t.open,full:t.full,cancelled:t.cancelled,completed:t.completed})[status]}
export function requestLabel(locale:Locale,status:JoinRequestStatus){const t=matchCommunityCopy[locale];return ({pending:t.pending,approved:t.approved,rejected:t.rejected,withdrawn:t.withdrawn,expired:t.expired})[status]}
export function participantLabel(locale:Locale,status:ParticipantStatus){const t=matchCommunityCopy[locale];return ({pending:t.pending,approved:t.approved,rejected:t.rejected,left:t.withdrawn})[status]}
export function matchTone(status:MatchStatus){return status==="open"?"success"as const:status==="full"?"warning"as const:status==="cancelled"?"danger"as const:"neutral"as const}
export function requestTone(status:JoinRequestStatus){return status==="approved"?"success"as const:status==="pending"?"warning"as const:status==="rejected"?"danger"as const:"neutral"as const}
export function positionLabel(locale:Locale,code:string){const labels:Record<string,{en:string;ar:string}>={goalkeeper:{en:"Goalkeeper",ar:"حارس مرمى"},defender:{en:"Defender",ar:"مدافع"},midfielder:{en:"Midfielder",ar:"وسط"},forward:{en:"Forward",ar:"مهاجم"}};return labels[code]?.[locale]??code.replaceAll("_"," ")}
export function isUpcoming(match:Match){return match.status!=="completed"&&match.status!=="cancelled"&&new Date(match.end_time).getTime()>Date.now()}
