import type { Locale } from "@/lib/copy";
export type RouteClass="LIVE"|"PARTIAL"|"SHELL"|"DEFERRED";export type ProductRoute={pattern:string;classification:RouteClass;area:string;title:Record<Locale,string>;description:Record<Locale,string>;auth?:boolean;role?:"owner"|"admin";nav?:"primary"|"secondary"|"dashboard"|"hidden";backend?:string;next:string};
const r=(pattern:string,classification:RouteClass,area:string,en:string,ar:string,descriptionEn:string,descriptionAr:string,options:Partial<ProductRoute>={}):ProductRoute=>({pattern,classification,area,title:{en,ar},description:{en:descriptionEn,ar:descriptionAr},nav:"hidden",next:"Future product sprint",...options});
export const productRoutes:ProductRoute[]=[
r("/","LIVE","home","Home","الرئيسية","Court discovery and booking entry.","اكتشاف الملاعب وبدء الحجز.",{nav:"primary",backend:"GET /courts",next:"Production review"}),
r("/courts","LIVE","courts","Courts","الملاعب","Browse real courts.","استعرض الملاعب الفعلية.",{nav:"primary",backend:"GET /courts",next:"Search and filters"}),r("/courts/:courtId","LIVE","courts","Court details","تفاصيل الملعب","Real court details and availability.","تفاصيل الملعب والمواعيد الفعلية.",{backend:"GET /courts/{id}; available-slots",next:"Reviews"}),
r("/bookings","LIVE","booking","My Bookings","حجوزاتي","Real booking history.","سجل الحجوزات الفعلي.",{auth:true,nav:"primary",backend:"GET /bookings/me",next:"E2E polish"}),r("/bookings/:bookingId","LIVE","booking","Booking details","تفاصيل الحجز","Real booking lifecycle.","دورة حياة الحجز الفعلية.",{auth:true,backend:"GET /bookings/{id}",next:"E2E polish"}),
r("/login","LIVE","auth","Log in","تسجيل الدخول","Secure account access.","دخول آمن للحساب.",{backend:"POST /auth/login",next:"Production review"}),r("/register","LIVE","auth","Create account","إنشاء حساب","Create a player account.","إنشاء حساب لاعب.",{backend:"POST /auth/register",next:"Production review"}),r("/profile","LIVE","account","Profile","الملف الشخصي","Current account details.","بيانات الحساب الحالية.",{auth:true,nav:"secondary",backend:"GET /users/me",next:"Editing blocked by backend"}),
r("/community","PARTIAL","community","Community","المجتمع الرياضي","Discover matches and community tools.","اكتشف المباريات وأدوات المجتمع.",{nav:"primary",backend:"Match endpoints",next:"Community workflows"}),r("/matches","LIVE","community","Find matches","اكتشف المباريات","Browse real public matches.","استعرض المباريات العامة الفعلية.",{nav:"primary",backend:"GET /matches",next:"Filters and pagination"}),r("/matches/:matchId","LIVE","community","Match details","تفاصيل المباراة","Real match participation state.","حالة المشاركة الفعلية.",{backend:"GET /matches/{id}",next:"Roster polish"}),r("/matches/new","PARTIAL","community","Create match","إنشاء مباراة","Match creation requires a confirmed booking.","إنشاء المباراة يتطلب حجزًا مؤكدًا.",{auth:true,backend:"POST /matches",next:"Creation form"}),r("/matches/me","PARTIAL","community","My matches","مبارياتي","Created and joined match views.","المباريات المنشأة والمنضم إليها.",{auth:true,backend:"GET /matches/me/*",next:"Management UI"}),r("/matches/requests","PARTIAL","community","Join requests","طلبات الانضمام","Review current match requests.","مراجعة طلبات المباريات الحالية.",{auth:true,backend:"GET /matches/me/join-requests",next:"Request management"}),
r("/players/:playerId","SHELL","players","Player profile","ملف اللاعب","Player profiles are not available yet.","ملفات اللاعبين غير متاحة بعد."),r("/teams","SHELL","teams","Teams","الفرق","Team features are coming later.","ميزات الفرق قادمة لاحقًا."),r("/teams/:teamId","SHELL","teams","Team details","تفاصيل الفريق","Team rosters and invitations are coming later.","قوائم الفرق والدعوات قادمة لاحقًا."),r("/tournaments","SHELL","tournaments","Tournaments","البطولات","Tournament discovery is planned.","اكتشاف البطولات مخطط له."),r("/tournaments/:tournamentId","SHELL","tournaments","Tournament details","تفاصيل البطولة","Fixtures, standings, and registration are planned.","المباريات والترتيب والتسجيل مخطط لها."),
r("/notifications","SHELL","account","Notifications","الإشعارات","Notifications are not connected yet.","الإشعارات غير متصلة بعد.",{auth:true,nav:"secondary"}),r("/reviews","PARTIAL","reviews","My reviews","تقييماتي","Review management backend exists; full UI is pending.","واجهة إدارة التقييمات قيد التنفيذ.",{auth:true,backend:"GET /reviews/me",next:"Reviews sprint"}),
r("/owner","PARTIAL","owner","Owner dashboard","لوحة المالك","Owner workspace foundation.","أساس مساحة عمل المالك.",{auth:true,role:"owner",nav:"dashboard",backend:"GET /owner/dashboard",next:"Owner operations"}),r("/owner/courts","PARTIAL","owner","Owner courts","ملاعب المالك","Court management foundation.","أساس إدارة الملاعب.",{auth:true,role:"owner",nav:"dashboard",backend:"/owner/courts",next:"Owner CRUD"}),r("/owner/bookings","PARTIAL","owner","Owner bookings","حجوزات المالك","Court booking operations foundation.","أساس عمليات حجوزات الملاعب.",{auth:true,role:"owner",nav:"dashboard",backend:"/owner/courts/{id}/bookings",next:"Court selector"}),r("/owner/calendar","PARTIAL","owner","Availability calendar","تقويم التوفر","Working hours and closures foundation.","أساس ساعات العمل والإغلاقات.",{auth:true,role:"owner",nav:"dashboard",backend:"Owner availability endpoints",next:"Calendar editor"}),r("/owner/pricing","PARTIAL","owner","Pricing","التسعير","Pricing rules foundation.","أساس قواعد التسعير.",{auth:true,role:"owner",nav:"dashboard",backend:"Owner pricing endpoints",next:"Pricing editor"}),r("/owner/reviews","PARTIAL","owner","Owner reviews","تقييمات المالك","Owner responses foundation.","أساس ردود المالك.",{auth:true,role:"owner",nav:"dashboard",backend:"Review response endpoints",next:"Owner responses"}),r("/owner/analytics","SHELL","owner","Analytics","التحليلات","Analytics are unavailable; no metrics are fabricated.","التحليلات غير متاحة ولا توجد أرقام مصطنعة.",{auth:true,role:"owner",nav:"dashboard"}),
r("/admin","SHELL","admin","Admin dashboard","لوحة الإدارة","Authorized administration foundation.","أساس الإدارة للمصرح لهم.",{auth:true,role:"admin",nav:"dashboard"}),...(["users","courts","bookings","matches","moderation"]as const).map(x=>r(`/admin/${x}`,"SHELL","admin",`Admin ${x}`,`إدارة ${x==="users"?"المستخدمين":x==="courts"?"الملاعب":x==="bookings"?"الحجوزات":x==="matches"?"المباريات":"المحتوى"}`,"Authorized shell; no administrative data is simulated.","واجهة مصرح بها دون محاكاة بيانات إدارية.",{auth:true,role:"admin",nav:"dashboard"})),
r("/payments","SHELL","payments","Payment history","سجل المدفوعات","No payment history service is connected.","لا توجد خدمة سجل مدفوعات متصلة.",{auth:true}),r("/payments/:paymentId","SHELL","payments","Payment status","حالة الدفع","Payment state requires verified server data.","حالة الدفع تتطلب بيانات موثقة من الخادم.",{auth:true}),r("/settings","SHELL","account","Settings","الإعدادات","Account preferences foundation.","أساس تفضيلات الحساب.",{auth:true,nav:"secondary"}),r("/settings/security","SHELL","account","Security settings","إعدادات الأمان","Security controls require backend support.","عناصر الأمان تتطلب دعم الخادم.",{auth:true}),r("/help","SHELL","legal","Help and support","المساعدة والدعم","Support channels are being prepared.","قنوات الدعم قيد الإعداد."),r("/privacy","SHELL","legal","Privacy","الخصوصية","Draft structure pending legal review.","مسودة بنية بانتظار المراجعة القانونية."),r("/terms","SHELL","legal","Terms","الشروط","Draft structure pending legal review.","مسودة بنية بانتظار المراجعة القانونية.")];
productRoutes.push(
  r("/courts/map","LIVE","courts","Court map","خريطة الملاعب","Map-ready view using verified court coordinates only.","عرض خريطة يستخدم إحداثيات الملاعب الموثوقة فقط.",{nav:"primary",backend:"GET /courts",next:"Map provider review"}),
  r("/bookings/new","LIVE","booking","Create booking","إنشاء حجز","Create a server-priced temporary hold.","إنشاء حجز مؤقت بسعر يحدده الخادم.",{auth:true,backend:"POST /bookings/hold",next:"E2E polish"}),
  r("/bookings/:bookingId/confirm","LIVE","booking","Booking hold","الحجز المؤقت","Track or release a real reservation hold.","متابعة أو إلغاء حجز مؤقت فعلي.",{auth:true,backend:"GET /bookings/{id}; cancel-hold",next:"Trusted confirmation integration"}),
  r("/bookings/:bookingId/success","LIVE","booking","Confirmed booking","الحجز المؤكد","Confirmed server state only.","حالة مؤكدة من الخادم فقط.",{auth:true,backend:"GET /bookings/{id}",next:"Production review"}),
  r("/owner/availability","PARTIAL","owner","Availability","التوفر","Availability rules foundation.","أساس قواعد التوفر.",{auth:true,role:"owner",nav:"dashboard",backend:"Owner availability endpoints",next:"Availability editor"}),
);
const match=(pattern:string,path:string)=>{const a=pattern.split("/").filter(Boolean),b=path.split("/").filter(Boolean);return a.length===b.length&&a.every((part,i)=>part.startsWith(":")||part===b[i])};
export const findProductRoute=(path:string)=>productRoutes.find(route=>!route.pattern.includes(":")&&match(route.pattern,path))??productRoutes.find(route=>match(route.pattern,path));
export const routeCounts=productRoutes.reduce<Record<RouteClass,number>>((acc,route)=>(acc[route.classification]++,acc),{LIVE:0,PARTIAL:0,SHELL:0,DEFERRED:0});
