import Image from "next/image";
import Link from "next/link";
import { Availability } from "@/components/availability";
import { Alert } from "@/components/ui/alert";
import { StatusBadge } from "@/components/ui/status-badge";
import { Surface } from "@/components/ui/surface";
import { ApiError } from "@/lib/types";
import { api } from "@/lib/api";
import { bookingUx,formatMoney } from "@/lib/booking-ux";
import { copy,type Locale } from "@/lib/copy";
export default async function CourtDetail({params}:{params:Promise<{locale:string;courtId:string}>}){const{locale,courtId}=await params,l=(locale==="en"?"en":"ar")as Locale,text=copy[l],ux=bookingUx[l];let court;try{court=await api.court(courtId);}catch(error){return <section className="page-wrap"><Link className="focus-ring text-sm font-bold text-[var(--brand)]" href={`/${l}/courts`}>{text.back}</Link><h1 className="mt-5 text-3xl font-black">{text.courtDetails}</h1><Alert tone="danger" message={error instanceof ApiError&&error.status===404?text.courtNotFound:ux.serviceError} className="mt-6"/></section>}const name=court[l==="ar"?"name_ar":"name_en"],description=court[l==="ar"?"description_ar":"description_en"];return <section className="page-wrap"><Link className="focus-ring text-sm font-bold text-[var(--brand)]" href={`/${l}/courts`}>{text.back}</Link><div className="mt-5 grid min-w-0 gap-7 lg:grid-cols-[1.35fr_.65fr]"><article className="min-w-0 space-y-5"><div className="relative aspect-[16/8] overflow-hidden rounded-[var(--radius-lg)] bg-[var(--surface-2)]">{court.image_url?<Image src={court.image_url} alt="" fill sizes="(max-width:1024px) 100vw, 65vw" className="object-cover" unoptimized/>:<div className="flex h-full items-center justify-center font-bold text-[var(--text-muted)]" aria-hidden="true">{text.courts}</div>}</div><Surface padding="lg"><div className="flex flex-wrap items-center justify-between gap-3"><StatusBadge status={court.is_active?"success":"danger"}>{court.is_active?text.courtOpen:text.courtUnavailable}</StatusBadge>{court.sport&&<span className="text-sm text-[var(--text-muted)]">{court.sport[l==="ar"?"name_ar":"name_en"]}</span>}</div><h1 className="mt-5 break-words text-3xl font-black">{name}</h1><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-[var(--text-muted)]">{ux.location}</dt><dd className="mt-1 break-words">{court.area}{court.address?` · ${court.address}`:""}</dd></div>{court.price_per_hour&&<div><dt className="text-sm text-[var(--text-muted)]">{ux.priceFrom}</dt><dd className="mt-1 font-bold"><bdi>{formatMoney(l,court.price_per_hour,court.currency)}</bdi> {ux.perHour}</dd></div>}</dl>{description&&<section aria-labelledby="court-description"><h2 id="court-description" className="sr-only">{text.courtDetails}</h2><p className="mt-6 leading-7 text-[var(--text-secondary)]">{description}</p></section>}</Surface></article><aside className="min-w-0 h-fit lg:sticky lg:top-24"><Surface padding="md"><h2 className="text-xl font-black">{text.courtAvailability}</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{text.courtAvailabilityDescription}</p><Availability courtId={courtId} locale={l} inactive={!court.is_active}/></Surface></aside></div></section>}
